name: ${HOSTNAME:? You need to set HOSTNAME env variable}

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

# enabled modules for monitoring (e.g. elasticsearch-xpack)
metricbeat.modules:
# - module: elasticsearch
#   xpack.enabled: true
#   period: 10s
#   hosts: ["http://node01:9200"]
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - event
      - healthcheck
      - info
      - memory
      - network
    period: 5s
    hosts: ["unix:///var/run/docker.sock"]

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
